### ISSUE TITLE
materialize error for rel-amazon

### ISSUE THREAD

**Issue by rishabh-ranjan** [snap-stanford/relbench#153]
i have pip installed pytorch_frame from the github main branch (pip list shows version 0.2.2). please see the traceback below:
```
Traceback (most recent call last):
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/lfs/ampere1/0/ranjanr/relbench-expts/scripts/gnn_node.py", line 233, in <module>
    main(args)
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/expt.py", line 66, in wrap
    main(store, args)
  File "/lfs/ampere1/0/ranjanr/relbench-expts/scripts/gnn_node.py", line 41, in main
    data, col_stats_dict = make_pkey_fkey_graph(
  File "/lfs/ampere1/0/ranjanr/relbench-expts/relbench/relbench/external/graph.py", line 95, in make_pkey_fkey_graph
    dataset = Dataset(
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/torch_frame/data/dataset.py", line 594, in materialize
    self._col_stats[col] = compute_col_stats(
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/torch_frame/data/stats.py", line 179, in compute_col_stats
    stats = {
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/torch_frame/data/stats.py", line 180, in <dictcomp>
    stat_type: stat_type.compute(ser.dropna(), sep)
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/torch_frame/data/stats.py", line 117, in compute
    ser = ser.apply(lambda row: MultiCategoricalTensorMapper.
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/pandas/core/series.py", line 4630, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/pandas/core/apply.py", line 1025, in apply
    return self.apply_standard()
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/pandas/core/apply.py", line 1076, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2834, in pandas._libs.lib.map_infer
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/torch_frame/data/stats.py", line 117, in <lambda>
    ser = ser.apply(lambda row: MultiCategoricalTensorMapper.
  File "/lfs/ampere1/0/ranjanr/.micromamba/envs/relbench-expts/lib/python3.8/site-packages/torch_frame/data/mapper.py", line 158, in split_by_sep
    raise ValueError(
ValueError: MulticategoricalTensorMapper only supports str or list types (got input: ['Books' 'Literature & Fiction' 'Dramas & Plays'])
````

**Comment by yiweny** [comment]
@rishabh-ranjan Is this still an issue? I can take a look at it.

**Comment by rishabh-ranjan** [comment]
no, @weihua916 fixed it in some PR.
