### ISSUE TITLE
gnn_link.py issues after refactoring

### ISSUE THREAD

**Issue by Kh4L** [snap-stanford/relbench#222]
`python gnn_link.py --dataset=rel-amazon --task=user-item-purchase --epochs 100 --eval_epochs_interval 1`
```
Traceback (most recent call last):
  File "/workspace/relbench/examples/gnn_link.py", line 64, in <module>
    data, col_stats_dict = make_pkey_fkey_graph(
  File "/usr/local/lib/python3.10/dist-packages/relbench/external/graph.py", line 93, in make_pkey_fkey_graph
    dataset = Dataset(
  File "/usr/local/lib/python3.10/dist-packages/torch_frame/data/dataset.py", line 594, in materialize
    self._col_stats[col] = compute_col_stats(
  File "/usr/local/lib/python3.10/dist-packages/torch_frame/data/stats.py", line 166, in compute_col_stats
    raise TypeError("Numerical series contains invalid entries. "
TypeError: Numerical series contains invalid entries. Please make sure your numerical series contains only numerical values or nans.
```
`python gnn_link.py --use_shallow  --dataset=rel-stack --task=post-post-related --epochs 2`
```
Traceback (most recent call last):
  File "/workspace/relbench/examples/gnn_link.py", line 64, in <module>
    data, col_stats_dict = make_pkey_fkey_graph(
  File "/usr/local/lib/python3.10/dist-packages/relbench/external/graph.py", line 118, in make_pkey_fkey_graph
    assert (pkey_index < len(db.table_dict[pkey_table_name])).all()
AssertionError
```

**Comment by Kh4L** [comment]
@rishabh-ranjan

**Comment by rishabh-ranjan** [comment]
These should be fixed now.
